name: docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

job:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACESS_TOKEN }}


      - 
