name: springboot-docker
on:
  push:
    branches: [ main ]
job:
  docker:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        windows: [windows-2019, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.windows }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACESS_TOKEN }}

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Buid and Push
        uses: docker/buid-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ screts.DOCKERHUB_USERNAME}}/Springboot-docker
      
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest}}
